#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

set -Eeuo pipefail

if [ "$RUNNER_OS" == "Linux" ]; then
    # gcc-13 -> g++-13
    sudo apt-get install --yes "${@//gcc/g++}"
elif [ "$RUNNER_OS" == "macOS" ]; then
    for ARG in "$@"; do
        # clang-15 -> llvm@15, gcc-13 -> gcc@13
        if [[ $ARG == clang* || $ARG == gcc* ]]; then
            ARG=$(echo ${ARG/clang/llvm} | awk -F '-' '{print $1"@"$2}')
        fi
        brew install --quiet $ARG
    done
else
    echo "OS ${$RUNNER_OS} is not supported"
    exit 1
fi
