# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: Report Artifacts

on:
  workflow_run:
    workflows:
      - Build Containers
    types:
      - completed
    branches-ignore:
      - main

concurrency:
  group: report-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan'
    steps:
      - name: Get PR number
        env:
          GH_TOKEN: ${{ github.token }}
        id: get_pr_number
        run: |
          # There is github.event.workflow_run.pull_requests, but it is always empty when the PR is from a fork.
          number=$(gh api \
            -XGET \
            -H "Accept: application/vnd.github+json" \
            /repos/seqan/actions/pulls \
            -F head=${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }} \
            -F state=all \
            -q '.[0] .number')
          echo "pr_number=${number}" >> $GITHUB_OUTPUT

      - name: Create Comment Body
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/seqan/actions/actions/runs/${{ github.event.workflow_run.id }}/artifacts > artifacts.json
          {
            echo "Artifacts available for download:"
            echo "| Artifact Name | Download Link |"
            echo "|---------------|---------------|"
            jq -r '.artifacts[] | "| \(.name) | https://github.com/seqan/actions/actions/runs/${{ github.event.workflow_run.id }}/artifacts/\(.id) |"' artifacts.json | sort
          } > report.md

      - name: Find Comment
        uses: peter-evans/find-comment@v4
        id: find_comment
        with:
          issue-number: ${{ steps.get_pr_number.outputs.pr_number }}
          body-includes: Artifacts available for download

      - name: Create
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ steps.get_pr_number.outputs.pr_number }}
          body-path: report.md
          edit-mode: replace
